### ISSUE TITLE
Custom fee below 0.1

### ISSUE THREAD

**Issue by halfik** [Samourai-Wallet/samourai-wallet-android#132]
There is no way to set custom fee below 1sat/b.
I have tested this on lastest version available on google play store.

**Comment by victorperin** [comment]
Why we even have a limit for that? This should be responsability of the user. At maximun an alert advising the user that the transaction might not be accepted.

**Comment by victorperin** [comment]
Yes, because it was a really small quantity when they were configured. If you live in a 3rd world country, this still makes difference.

Also, it blocks the user to do something that's not specified in the protocol. If an user wants to send a custom fee below that, i don't think the best way is to block it. At maximum show some kind of message telling the user that maybe this transaction don't go through the network.

**Comment by SamouraiDev** [comment]
Our experience has shown that many users, if allowed, will set the fee too low and the transaction will not be relayed. We have no plans to go lower than 1 sat/b.
