### ISSUE TITLE
Feature request: Support Bech32 with PayNym?

### ISSUE THREAD

**Issue by jonathancross** [Samourai-Wallet/samourai-wallet-android#193]
From what I can see, a PayNym will generate legacy P2PKH receiving addresses.
Would be great if Bech32 addresses could be used instead (for lower fees when spending).

**Comment by RockyRococo** [comment]
Samourai just released this blog post with their latest update (0.98.75), which seems to suggest that what you describe is already in the works:

> Unseen Changes
An important under the hood change in the way your wallet keeps track of PayNym’s means your PayNym bot will very soon generate Segwit Native (bech32) addresses by default instead of legacy addresses. This change, in combination with many more planned updates will make using PayNym’s cheaper, faster, and easier than ever. 

[https://blog.samouraiwallet.com/post/176412126502/the-road-to-10-ui-update](url)

**Comment by SamouraiDev** [comment]
Yes, the groundwork has been laid and segwit support for PayNyms will be available very soon.

**Comment by jonathancross** [comment]
Thanks @RockyRococo! Yes, I see this in the blog post:

> An important under the hood change in the way your wallet keeps track of PayNym’s means your PayNym bot will very soon generate Segwit Native (bech32) addresses by default instead of legacy addresses. This change, in combination with many more planned updates will make using PayNym’s cheaper, faster, and easier than ever.

**Comment by SamouraiDev** [comment]
Done.
