### ISSUE TITLE
"SEND" button does not appear sometimes

### ISSUE THREAD

**Issue by theihor** [Samourai-Wallet/samourai-wallet-android#26]
When I input the amount in USD green "SEND" button does not appear.
I played with inputs a bit and as far as I understand this button appears only when all input fields are valid.

When you input amount in USD, corresponding amount in BTC is with comma (`,`) and not with dot (`.`) which is not valid enough for button to appear. If you input amount in BTC, the corresponding value in USD also is with comma, but the button appears normally.
And you are not able to input comma manually neither in BTC nor in USD field.

Also, I am not an expert in interface design, but personally I would like for "SEND" button to always be there, and if something is wrong with input fields, get a message about it.
Because when you scan someone's address, then input something and then there is no SEND button, it's really confusing.

**Comment by samouraiwallet** [comment]
Thank you @theihor for your report. I suspect this comes down to a localisation issue with the comma ( , ) being used instead of a full stop ( . ) 

If you change your system language to English I bet it would fix this issue. We will look into fixing. 

> Also, I am not an expert in interface design, but personally I would like for "SEND" button to always be there, and if something is wrong with input fields, get a message about it.
Because when you scan someone's address, then input something and then there is no SEND button, it's really confusing.

You aren't the first to be confused by this and we will likely change this behaviour in the future. 

Thanks

SW

**Comment by SamouraiDev** [comment]
Fixed in build 0.92.56.
