### ISSUE TITLE
Numeric value input issues in locales using different decimal separator than US-English

### ISSUE THREAD

**Issue by bjd** [Samourai-Wallet/samourai-wallet-android#47]
I'm using the Dutch language and input settings on my phone and therefore number use `.` as thousand separator and `,` as decimal separator. Since the numeric value input keypad only has `.` I cannot enter fractional values. For example if I want to send 0.001 BTC this gets interpreted as 1 BTC. 

![input_locale_issue](https://user-images.githubusercontent.com/97059/31862697-7fdc66c8-b742-11e7-948d-afab4887d71c.png)

As a workaround I can switch my phone to US-English language, but this is not ideal of course.

**Comment by bjd** [comment]
Digging a little further this maybe could also be considered android/samsung bug. Switching to different keyboard (gboard) does allow input of both `.` and `,`.

**Comment by bjd** [comment]
Looks like a long standing issue in android and apparently only fixed recently for Oreo:
https://issuetracker.google.com/issues/36907764

I don't know if this can somehow be handled elegantly (perhaps enforce US locale on amount inputs?) as I imagine this could trip up a lot of people. Otherwise feel free to close this issue.

**Comment by samouraiwallet** [comment]
Thanks for all the research you did on this topic. We have been dealing with the (,) and (.) seperator issues for some time, it seems we fix one locale and another breaks. I was unaware of the samsung conncection and was often confused because I wasn't able to replicate the issues (using gboard).

We are building a custom keyboard that will simply enforce one method of unit separation and always be in use, bypassing the OS keyboard. 

I'll let @SamouraiDev choose to close the ticket if he feels appropriate as he runs the repo. Thanks again for you research on the matter.

**Comment by SamouraiDev** [comment]
Modifications have been made in v0.96.03.
