### ISSUE TITLE
Ledger Hardware Wallet support

### ISSUE THREAD

**Issue by sulliwane** [Samourai-Wallet/samourai-wallet-android#96]
Like [Mycellium](https://ledger.zendesk.com/hc/en-us/articles/115005199449-Ledger-Bitcoin-Wallet-on-Android),

is it planned to add support for LEDGER Hardware Wallet signing ? [Mycellium does not support segwit address](https://github.com/mycelium-com/wallet-android/issues/379), so useless if the BTC are on a segwit address in the hardware wallet...

Please :+1:  this issue if you'd like to see support for Ledger nano implemented (similar to Mycellium).

Many Thanks for the great work!

**Comment by SamouraiDev** [comment]
We are working on Trezor integration, yes.

**Comment by sulliwane** [comment]
Any idea if it is the same standard as Ledger ?

**Comment by SamouraiDev** [comment]
No idea. We are targeting Trezor, in any case.

**Comment by sulliwane** [comment]
Ok @SamouraiDev, many thanks for your answer. 

Then I just edited my question to make it ledger specific, so users can track here the state of the support for Ledger.

Please :+1:  this issue if you'd like to see support for Ledger nano implemented (similar to Mycellium).

**Comment by 2pac1** [comment]
we want and need ledger support

**Comment by SamouraiDev** [comment]
No Ledger support forthcoming.

**Comment by sulliwane** [comment]
Thanks @SamouraiDev for your answer. May I ask why supporting Trezor and not supporting Ledger?

**Comment by rebroad** [comment]
@SamouraDev isn't the ledger the favoured hardware device these days?

**Comment by SamouraiDev** [comment]
Out of the question.

**Comment by balresch** [comment]
I do not get this response. @SamouraiDev could you please elaborate?

**Comment by SamouraiDev** [comment]
Out of the question. No.

**Comment by balresch** [comment]
Ok cool. So there is a reason but you are not sharing it, keeping your would-be-userbase uneducated? Cool. /s

**Comment by SamouraiDev** [comment]
KYC, guy. Google is your friend here.

**Comment by sulliwane** [comment]
I agree with @balresch, That would be nice being more explicit with your users. Is that Trezor is sponsoring and not Ledger ? Or personal disagreement with Ledger company ? We all respect and love the great work being done on this project, and more transparency with your users on this question would be very welcome :) thanks

**Comment by balresch** [comment]
I know how to Google, I know what a KYC is - I still have no clue what you are talking about. I would not ask if I felt the answer was obvious. You seem to think the answer is obvious, but you are heavily biased in that regard. Please note that to me, a quite tech-savy want-to-be-user (who already owns a Ledger and wants to buy a GoTenna), it is not obvious. Hence my question. Thank you for your efforts.

**Comment by 2pac1** [comment]
Agree.
Why Trezor first over Ledger?

**Comment by SamouraiDev** [comment]
> I know how to Google, I know what a KYC is - I still have no clue what you are talking about. I would not ask if I felt the answer was obvious. You seem to think the answer is obvious, but you are heavily biased in that regard. Please note that to me, a quite tech-savy want-to-be-user (who already owns a Ledger and wants to buy a GoTenna), it is not obvious. Hence my question. Thank you for your efforts.

Very sorry. Didn't realize I was here to "enlighten" you. DYOR. Ledger is associated w/ KYC outfits and will have no entry point into Samourai Wallet. End of story.

**Comment by rawlinc** [comment]
For the benefit of anybody following this thread, I have to assume that @SamouraiDev is referring to the fact that Ledger (the company) also provides enterprise services:

> "We offer fully customizable infrastructure solutions safeguarding crypto assets for Banks, Hedge Funds and High Net Worth individuals. We also work together with big players in various industries on blockchain use cases." -Ledger Website

If Ledger has managed to sell their custody/HSM solutions to centralized exchanges or banks, then I guess Ledger is "associated" with organizations that collect KYC data. This "association" makes no sense in determining whether or not to add Ledger support to the Samourai wallet. In no way does using a Ledger hardware wallet expose you to KYC data collection and the associated privacy issues that come along with that. The Samourai dev's argument is equivalent to saying something like "I'm not going release a version of my software for Windows because Microsoft sold a copy of Windows to <insert political organization you don't agree with>".

@sulliwane Mycelium recently [replied to a google play review](https://play.google.com/store/apps/details?id=com.mycelium.wallet&reviewId=gp%3AAOqpTOHL3WhpXniG3C4MV4IbOJW37UfuLPMCOV59703gbp2IIBK2yGFF7qI9UkDoHSJs8c9H2YdyQ-JBFO-mxg) and said segwit support will be available this month which means their Ledger integration will actually be useful. Also Ledger mentioned in a [blog post](https://www.ledger.fr/2018/02/23/announcing-new-ledger-wallet-desktop-mobile-applications/) that a mobile (Android, iOS) version of their software is in their roadmap.

**Comment by SamouraiDev** [comment]
Nothing to do with the above.

**Comment by brandonsandoval** [comment]
You're doing more harm then good by deliberately planning to not support the ledger for whatever your nontransparent reason is. 

Ledger users that want to use there phones, would have to risk a small stake of bitcoins on there mobiles outside of there hardware wallet, or buy another hardware wallet, a trezor, which not 100% of your userbase are going to do this. 

If you supported both, then both hardware wallet users would have a higher safely means of using there phones/samourai wallet in conjunction with a hardware wallet.
